### PR TITLE
Prepare version 4.0.8

### PR DESCRIPTION
**Pull request by sippsolutions**
Merged tag 4.0.7 into master, changed version to 4.0.8 so that 4.0.8 contains the code of 4.0.7 as well as the fixes for #264

### CODE REVIEW

**Comment by sippsolutions** [comment]
@paulmillr

**Comment by ppvg** [comment]
TL;DR: this PR should probably be closed, see #266.

If I understood correctly, `main` contains breaking changes and 4.0.6 was **erroneously** tagged from `main`. 4.0.7 was released from the `v4` branch to address this, but doesn't contain the fix for #264. Instead of releasing again from `main`, the fix for #264 needs to be backported to the `v4` branch first, which is what #266 does.

**Comment by paulmillr** [comment]
the idea was to release v5 on `main` with the breaking changes, but I don't think that would happen soon.

**Comment by ppvg** [comment]
Even if that did happen soon, it would still be a good idea to release a v4 update with the backported fix regardless.

**Comment by paulmillr** [comment]
v4 is fine, but I think we should go back to single main branch

**Review by andyren0110 — APPROVED** [review]

**Pull request closed without merging**
