### PR TITLE
Fix ci

### PR DESCRIPTION
**Pull request by dclayton-diig**
CI was failing because some tests are written for Windows, and some are written for Posix.

### CODE REVIEW

**Comment by doowb** [comment]
Please change the double quotes `"` back to single quotes `'`. All those changes makes it hard to see the actual change.

**Comment by dclayton-diig** [comment]
@doowb Updated to single quotes as requested

**Comment by dclayton-diig** [comment]
I've noticed that the build is also failing in master; do you have a commit ID / branch where this works and I can take a look?

Lines 107 and 108 (in master):

`      let fixtures = ['a\\a', 'a\\b', 'a\\c', 'b\\a', 'b\\b', 'b\\c'];
      assert.deepEqual(mm(fixtures, '!*/*', { format }), fixtures);`

Are identical to lines 158 and 159 with the exception of the expected outcome and overriding the path separator on line 130:

`      let fixtures = ['a\\a', 'a\\b', 'a\\c', 'b\\a', 'b\\b', 'b\\c'];
      assert.deepEqual(mm(fixtures, '!*/*'), []);`

What's happening is that:

* On Linux / Mac builds the path.separator is '/' by default, so all tests pass because the override on line 130 forces the separator
* On Windows path.separator is '//' by default - the test "posix paths (array of patterns)" does not override the separator, so the outcome of the test on line 108 is "[]".  This fails because it's asserting against the fixtures that would be produced using /, but the system is producing output using //

This can be fixed by one of the following:

1. Create a set of tests that just run on Windows (as per the pull request), or
1. Explicitly set the operator to "/" in the posix tests.  

What are your thoughts?

**Comment by kibertoad** [comment]
@jonschlinkert Is there anything I can do to help get this PR merged?

**Comment by jonschlinkert** [comment]
@kibertoad I believe these tests should be passing on any OS. I think we either need to rethink how these tests are done, so they are more appropriate for all platforms, or fix whatever bug is causing the tests to fail.

**Comment by jonschlinkert** [comment]
Closing since bypassing unit tests is not a good way to do unit tests. I'd much rather ensure those tests pass on windows.

**Pull request closed without merging**
